### PR TITLE
Add new background images

### PR DESCRIPTION
**Pull request by zsotroav**

### CODE REVIEW

**Review by duncte123 — COMMENTED** [review]
not sure if "tents" is a good name for the outside view of the tent

**Comment by zsotroav** [comment]
> not sure if "tents" is a good name for the outside view of the tent

do you have any better ideas? Because I didn't...

**Comment by MorphTuple** [comment]
Here are some (terrible) suggestions
`beachtent`
`seaside`
`seasidetent`
`seatent`
`outsidetent`

**Comment by duncte123** [comment]
What about `tent_outside` and `tent_inside`?

**Review by duncte123 — APPROVED** [review]

**Pull request merged**
